# Generated by Django 4.1.5 on 2023-03-16 05:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videogroup',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='videogroup',
            old_name='video_id',
            new_name='video',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'group')},
        ),
    ]
