# Generated by Django 4.1.5 on 2023-02-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='video',
            name='stored_at',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
