# Generated by Django 4.1.5 on 2023-05-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
